### ISSUE TITLE
Trackpad e teclado não funcionam

### ISSUE THREAD

**Issue by ricardomartiinas** [YuryRegis/Acer-Nitro5-AN515-54-58CL-Monterey#2]
Boa noite Yury, poderia me ajudar por favor, tava usando o big sur no nitro 5 an515-54 e tudo funcionava. Instalei o monterey mas não consigo fazer o trackpad e o teclado funcionarem, me ajuda por favor. Obrigado

**Comment by YuryRegis** [comment]
Ola @ricardomartiinas 

Se me lembro bem este era um problema conhecido. Para o trackpad e o teclado integrado funcionar corretamente, você não pode interagir com os mesmos após iniciar o processo de boot do macOS. Aguarde até que o sistema seja carregado e a tela de bem-vindo / Login apareça. A partir deste ponto você já pode interagir com o teclado e trackpad integrado do seu notebook.

Recomendo usar o repositório do [BigSur](https://github.com/YuryRegis/Acer-Nitro5-AN515-54-58CL-BigSur) pois temos algumas correções de outros problemas conhecidos como gráfico integrado, por exemplo.
